### ISSUE TITLE
Unexpected execution order and failure with duplicated test names

### ISSUE THREAD

**Issue by lwasyl** [kotest/kotest#2915]
I tried with Kotest 5.0 and later updates

The issue seems to be related to be triggered by two tests _not on the same level_ having the same name. The following tests should work: each `load()` is properly followed by a `complete()`, and the tests pass on Kotest 4.x. However, on 5.x they fail with two exceptions: one somewhere in JUnit code, the other in the `FakeService`. Looks like either `InstancePerLeaf` is not respected, or the execution order is just messed up because of the duplicated names.

Renaming one of the duplicated test names causes the tests to pass, also removing some `it`s (I think).

This behavior is unexpected, because the "duplicated" test names appear on different levels. My understanding was that the names are considered duplicate on the same tests level only.

Repro:

```kotlin
package com.example
​
import io.kotest.core.TestConfiguration
import io.kotest.core.spec.IsolationMode
import io.kotest.core.spec.style.DescribeSpec
import kotlinx.coroutines.CompletableDeferred
import kotlinx.coroutines.Job
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import kotlinx.coroutines.test.TestCoroutineScope
​
fun TestConfiguration.customTestScope() = TestCoroutineScope(Job()).also { testScope ->
    afterSpec {
        testScope.cancel()
        testScope.cleanupTestCoroutines()
    }
}
​
internal class Repro : DescribeSpec() {
​
    override fun isolationMode() = IsolationMode.InstancePerLeaf
​
    private val service = FakeService()
​
    init {
        describe("test") {
            val load: suspend () -> Unit = { runCatching { service.await() } }
​
            describe("foo") {
                customTestScope().launch { load() }
​
                it("a") {}
​
                it("b") {}
​
                describe("THIS TEST NAME IS DUPLICATED") {
                    service.complete()
​
                    it("a") {}
​
                    it("b") {}
                }
​
                describe("bar") {
                    service.complete()
​
                    it("a") {}
​
                    it("b") {}
​
                    describe("baz") {
                        customTestScope().launch { load() }
​
                        it("a") {}
​
                        it("b") {}
​
                        describe("THIS TEST NAME IS DUPLICATED") {
                            service.complete()
​
                            it("a") {}
​
                            it("b") {}
                        }
                    }
                }
            }
        }
    }
}
​
class FakeService {
​
    var deferred: CompletableDeferred<Unit>? = null
​
    suspend fun await() {
        if (deferred != null) error("Can't await without completing first")
​
        val cd = CompletableDeferred<Unit>()
        deferred = cd
​
        val value = runCatching { cd.await() }
        deferred = null
        value.getOrThrow()
    }
​
    fun complete() {
        deferred!!.complete(Unit)
    }
}
```

**Comment by Kantis** [comment]
Feels related to #2884

**Comment by lwasyl** [comment]
Yep, looks like exactly the same issue, thanks for pointing me to it! I'll keep both opened just in case though, as both have clear repros that can be verified.

**Comment by sksamuel** [comment]
This seems to only be with instancePerLeaf

**Comment by sksamuel** [comment]
Fixed in master.

**Comment by lwasyl** [comment]
@sksamuel Seems like there's still an issue with duplicated tests names in 5.3.0, with slightly different repro (simplified compared to the original):

```kotlin
import io.kotest.core.spec.IsolationMode
import io.kotest.core.spec.style.DescribeSpec
import io.kotest.matchers.shouldBe

internal class TestTest : DescribeSpec() {

    override fun isolationMode() = IsolationMode.InstancePerLeaf

    init {
        var i = 0

        describe("test") {
            i += 1

            describe("foo") {
                i += 1

                it("a") {
                    i shouldBe 2
                }

                it("b") {
                    i shouldBe 2
                }

                describe("THIS TEST NAME IS DUPLICATED") {
                    i += 1

                    it("a") {
                        i shouldBe 3
                    }

                    it("b") {
                        i shouldBe 3
                    }
                }

                describe("bar") {
                    i += 1

                    it("a") {
                        i shouldBe 3
                    }

                    it("b") {
                        i shouldBe 3
                    }

                    describe("THIS TEST NAME IS DUPLICATED") {
                        i += 1

                        it("a") {
                            i shouldBe 4
                        }

                        it("b") {
                            i shouldBe 4
                        }
                    }
                }
            }
        }
    }
}
```

And the failure:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/3951580/173231930-d72cbb5f-6641-4df1-8295-9665aa8154eb.png">

(let me know if I should open a new issue)
