### ISSUE TITLE
StackOverFlow when using Arb.stringPattern()

### ISSUE THREAD

**Issue by ssibongee** [kotest/kotest#3399]
**kotest 4.4.1**

I am encountering a bug when using the Arb.stringPattern() method from the io.kotest.property.Arb class. The method is throwing a StackOverflowError exception, and I am unable to generate arbitrary values for my test cases.

Here's a code snippet that demonstrates the issue:
```kotlin
private const val EMAIL_REGEX_PATTERN =  "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"

fun email() = Arb.stringPattern(EMAIL_REGEX_PATTERN).single()
```
The Arb.stringPattern method is supposed to generate arbitrary strings that match the specified pattern, but it is throwing the following error:
<img width="634" alt="image" src="https://user-images.githubusercontent.com/54518332/218003608-7f6a8725-9c2b-4cf4-8e31-4629d9bf5e9f.png">

I've confirmed that io.kotest.proeprty.Arb uses Generex internally and I've checked issues like [StackOverflowError from pattern input #56](https://github.com/mifmif/Generex/issues/56) in Generex's Github Repository. In my opinion, there are potential problems with using Generex.

I would appreciate your help in resolving this issue. Please let me know if you need any additional information or if there is a workaround for this bug.

**Comment by Kantis** [comment]
I'm unable to replicate this issue on master branch with JDK 11. Perhaps this has been fixed in Rgxgen already?

**Comment by ssibongee** [comment]
May I know which version did you test on? I am using by adding the following dependencies, and I use JDK 11 version, but the problem still persists.
```gradle
        testImplementation("io.kotest:kotest-runner-junit5-jvm:4.4.1")
        testImplementation("io.kotest:kotest-property:4.4.1")
```

**Comment by Kantis** [comment]
I tested on kotest 5.5.5
