### ISSUE TITLE
[6.0.0M3] Defective POMs leading to "'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing."

### ISSUE THREAD

**Issue by andrew-shewring-tr** [kotest/kotest#4860]
**Which version of Kotest are you using**
6.0.0M3

When running the build, errors (really warnings) like the following are shown - it would be great if the various POMs could be corrected so that these don't pollute build logs:

```
Errors occurred while building effective model from /home/runner/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-common/6.0.0.M3/725b4645c0248c44058a8310c244abbbf45bdf8a/kotest-common-6.0.0.M3.pom:
	'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. in io.kotest:kotest-common:6.0.0.M3
Errors occurred while building effective model from /home/runner/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-framework-engine/6.0.0.M3/373307b5ef107f8c0dda5b8cdbd8cf165d14c949/kotest-framework-engine-6.0.0.M3.pom:
	'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. in io.kotest:kotest-framework-engine:6.0.0.M3
Errors occurred while building effective model from /home/runner/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-assertions-shared/6.0.0.M3/1e7f41d1a803665040ad105910dd67cf9f6c8db/kotest-assertions-shared-6.0.0.M3.pom:
	'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. in io.kotest:kotest-assertions-shared:6.0.0.M3
Errors occurred while building effective model from /home/runner/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-assertions-core/6.0.0.M3/9d86c31eded70f63195f4915d0f17519d99e77b5/kotest-assertions-core-6.0.0.M3.pom:
	'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. in io.kotest:kotest-assertions-core:6.0.0.M3
Errors occurred while building effective model from /home/runner/.gradle/caches/modules-2/files-2.1/io.kotest/kotest-property/6.0.0.M3/15e1a38c91da3a6ec5a94160106998fe667129d4/kotest-property-6.0.0.M3.pom:
	'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. in io.kotest:kotest-property:6.0.0.M3
```

**Comment by andrew-shewring-tr** [comment]
Example POM without version for `kotlin-reflect`:

```
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-reflect</artifactId>
      <scope>runtime</scope>
    </dependency>
```


[kotest-common-6.0.0.M3.pom.txt](https://github.com/user-attachments/files/19936254/kotest-common-6.0.0.M3.pom.txt)

**Comment by andrew-shewring-tr** [comment]
Should be fixed in https://github.com/kotest/kotest/pull/4861

**Comment by gab1sv** [comment]
seems to be still an issue in 6.0.0.M4

```
Errors occurred while building effective model from [..]\.gradle\caches\modules-2\files-2.1\io.kotest\kotest-assertions-shared\6.0.0.M4\8d4158342acd3c9df9b57318a6fb5f9730794072\kotest-assertions-shared-6.0.0.M4.pom:
	'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. in io.kotest:kotest-assertions-shared:6.0.0.M4
Errors occurred while building effective model from [..]\.gradle\caches\modules-2\files-2.1\io.kotest\kotest-common\6.0.0.M4\7d1614521bdac9e4c3857fade71ea5dd0a979cf4\kotest-common-6.0.0.M4.pom:
	'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. in io.kotest:kotest-common:6.0.0.M4
Errors occurred while building effective model from [..]\.gradle\caches\modules-2\files-2.1\io.kotest\kotest-framework-engine\6.0.0.M4\96d8e5e6e109562f9722aa13a7897a6a383b6ee7\kotest-framework-engine-6.0.0.M4.pom:
	'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. in io.kotest:kotest-framework-engine:6.0.0.M4
Errors occurred while building effective model from [..]\.gradle\caches\modules-2\files-2.1\io.kotest\kotest-assertions-core\6.0.0.M4\fbdf04dae2cb0d32514efbd1ebb6fcabbe5cdf8b\kotest-assertions-core-6.0.0.M4.pom:
	'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. in io.kotest:kotest-assertions-core:6.0.0.M4
```

@andrew-shewring-tr , what do you think?
