### ISSUE TITLE
Do not skip sibling context with failfast=true

### ISSUE THREAD

**Issue by PetrYako** [kotest/kotest#4944]
Kotest: 6.0.0.M5

if a test fails inside the container, the next sibling containers are also skipped
```kotlin
list.forEach { item ->
  context("when adding a new $item").config(failfast = true) {
    it("shows modal")         { /* … */ }
    it("closes the modal")    { /* … */ }   // ← fails here and skips all remained items in the list, marks context as skipped
    it("shows the new item")  { /* … */ }
  }
}
```
```kotlin
// Expected flow:
┌ context A (failfast = true)
│ ├ it 1   ✅
│ ├ it 2   ❌ → stop only context A
│ └ it 3   ⏭
└ context B                 ✅ still runs
```

**Comment by sksamuel** [comment]
Are you using isolation mode ?

**Comment by PetrYako** [comment]
@sksamuel no, I'm using the default setup without changing the isolation mode in code

**Comment by sksamuel** [comment]
Fixed in main.

**Comment by ricardorlg** [comment]
@sksamuel , sorry to reopen this, but I'm still getting the same error. Was the fix merged?

**Comment by sksamuel** [comment]
Fix going into 6.2
