### ISSUE TITLE
Kotest 6 breaks tests

### ISSUE THREAD

**Issue by koufa13** [kotest/kotest#5054]
**Which version of Kotest are you using**
Kotest 6.0.2

When using the Kotest 6 versions (6.0.0 - 6.0.2) mutliple tests are failing without any specific reason. 
Is there anything we have to define differently compared to Kotest 5.9 where this behaviour is not being observed and it works as expected? Is there any extra info we can provide for you for debugging ? Unfortunately it's difficult to create such a complex reproducer.

Our config: 

```
object KotestProjectConfig : AbstractProjectConfig() {
   override val extensions: List<Extension> = listOf(
        SystemPropertyTagExtension,
        SpecOrdering,
        MockImportsBeforeSpec,
        SpringExtension(),
        AllureTestReporter()
    )

    override val testExecutionMode: TestExecutionMode = TestExecutionMode.LimitedConcurrency(4)

    override val duplicateTestNameMode = DuplicateTestNameMode.Error
    override val tagInheritance = true
    override val timeout = 20L.seconds
    override val isolationMode = IsolationMode.SingleInstance
    override val failOnEmptyTestSuite = true
}
```

**Comment by koufa13** [comment]
Could be related to this: https://github.com/kotest/kotest/issues/5055

**Comment by sksamuel** [comment]
Before the edit, you had get() = list(...)
Is that what you have in real code? Because that would definitely cause it.

**Comment by koufa13** [comment]
@sksamuel Exactly that's why I had edited it. I found it out when writing this. This fixed the Allure issue I was experiencing but still a lot of tests fail in comparison to kotest 5.9

**Comment by huehnerlady** [comment]
Are you sure your test Config is found? Might be connected to https://github.com/kotest/kotest/issues/5016?

**Comment by sksamuel** [comment]
> [@sksamuel](https://github.com/sksamuel) Exactly that's why I had edited it. I found it out when writing this. This fixed the Allure issue I was experiencing but still a lot of tests fail in comparison to kotest 5.9

When you say tests failing, are you seeing exceptions? Is this in intellij / gradle / both?

**Comment by akoufa** [comment]
@huehnerlady I added some logs and if I am not mistaken the config is being used. 

@sksamuel I am using maven `./mvnw clean test -Dkotest.tags="backend"` . I am not sure what the exact error is, I am still debugging it. What I instantly see is

 Kotest 5.9:
`Tests run: 845, Failures: 18, Errors: 19, Skipped: 8`

Kotest 6:
`Tests run: 873, Failures: 771, Errors: 5, Skipped: 15`

We have the SpringExtension and we are executing Http requests. What I see is with Kotest 6 a lot of responses return Bad Request 400. Maybe the `WebClient` configuration is not correct with Kotest 6. The total number of tests is also different that's why I assume at the moment that the tag resolution is not working correctly in Kotest 6. I will try to create a reprocuer the next days.

**Comment by sksamuel** [comment]
Tag resolution is fixed in main, will be in 6.0.3.
Your other issue might be related to https://github.com/kotest/kotest/issues/5056 which I am working on now.

**Comment by sksamuel** [comment]
6.0.3 is out btw

**Comment by akoufa** [comment]
@sksamuel Just checked. Unfortunately still observing the same issues. I will retest after the #5056 is fixed.

**Comment by theRealGG** [comment]
I have a similar problem with the Testcontainer container extension which is not started.

**Comment by sksamuel** [comment]
https://github.com/kotest/kotest/issues/5056 is fixed if you want to retest?

**Comment by akoufa** [comment]
@sksamuel Issue is still happening. I just checked with Kotest 6.0.4 and almost all our are still failling when running `mvnw test`. I compared it, checking out our main branch, which still uses Kotest 5.9.1 and running again `mvnw test` no issues.

**Config with Kotest 5.9.1**

```
object KotestProjectConfig : AbstractProjectConfig() {
    override fun extensions(): List<Extension> =
        listOf(
            SystemPropertyTagExtension,
            SpecOrdering,
            MockImportsBeforeSpec,
            SpringExtension,
            SpringAutowireConstructorExtension,
            AllureTestReporter(),
        )

    override val parallelism = 4
    override val duplicateTestNameMode = DuplicateTestNameMode.Error
    override val tagInheritance = true
    override val timeout = 20L.seconds
    override val isolationMode = IsolationMode.SingleInstance
    override val failOnEmptyTestSuite = true
}

class DynamicActiveProfilesResolver : ActiveProfilesResolver {
    override fun resolve(testClass: Class<*>): Array<String> {
        val activeProfiles = System.getenv("KOTEST_PROFILES").split(',')
        return activeProfiles.toTypedArray()
    }
}
```

**Config with Kotest 6.0.4**

```
object KotestProjectConfig : AbstractProjectConfig() {
    override val extensions: List<Extension> =
        listOf(
            SystemPropertyTagExtension,
            SpecOrdering,
            MockImportsBeforeSpec,
            SpringExtension(),
            AllureTestReporter(),
        )

    override val testExecutionMode: TestExecutionMode = TestExecutionMode.LimitedConcurrency(4)

    override val duplicateTestNameMode = DuplicateTestNameMode.Error
    override val tagInheritance = true
    override val timeout = 20L.seconds
    override val isolationMode = IsolationMode.SingleInstance
    override val failOnEmptyTestSuite = true
}

class DynamicActiveProfilesResolver : ActiveProfilesResolver {
    override fun resolve(testClass: Class<*>): Array<String> {
        val activeProfiles = System.getenv("KOTEST_PROFILES").split(',')
        return activeProfiles.toTypedArray()
    }
}
```

Do you see any inconsistencies between our Kotest configs ?

**Comment by akoufa** [comment]
@sksamuel we are relying on a specific Spec ordering. It seems for me that Kotest 6 does not honour the ordering we are defining. Could that be the case?

**Comment by koufa13** [comment]
@sksamuel Original issue is fixed now.

**Comment by sksamuel** [comment]
Great
