### ISSUE TITLE
Kotest plugin shows only strack trace of first failing test in case of multiple test failure

### ISSUE THREAD

**Issue by ashishkujoy** [kotest/kotest#5515]
Please refer this screen recording posted on kotest-dev slack channel for reference   https://kotlinlang.slack.com/archives/CSYLDDZUY/p1588192925000100

**Comment by sksamuel** [comment]
Can you try latest kotest snaphot please as I believe this is fixed in that.

**Comment by ashishkujoy** [comment]
@sksamuel now i am getting error message expected:<2> but was:<3> but the stacktrace is still missing.
<img width="911" alt="Screenshot 2020-05-19 13 54 51" src="https://user-images.githubusercontent.com/34642693/82303286-5f5ae700-99d8-11ea-8433-02bd99132b33.png">

**Comment by sksamuel** [comment]
You're on 0.9.16+ and the latest console snapshot?

**Comment by ashishkujoy** [comment]
@sksamuel i had kotest plugin 0.90.18 but console runner was 4.0.5. I will try with the lastest console runner snapshot

**Comment by ashishkujoy** [comment]
@sksamuel Thanks its working properly with combination 0.90.18 plugin and 4.1.0.292-SNAPSHOT console runner
